import { ValidationPipe } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { NestFactory } from '@nestjs/core';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { GlobalExceptionFilter, ResponseInterceptor } from '@app/common';
import { LoggerService } from '@app/logger';
import helmet from 'helmet';
import { json, urlencoded } from 'express';
import { AppModule } from './app.module';

async function bootstrap(): Promise<void> {
  const app = await NestFactory.create(AppModule, { bodyParser: false });
  const configService = app.get(ConfigService);

  app.setGlobalPrefix('api');

  const nodeEnv = configService.get<string>('app.nodeEnv', 'development');
  const corsOriginsRaw = configService.get<string>(
    'gateway.corsOrigins',
    'http://localhost:4000,http://127.0.0.1:4000,http://localhost:4008,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000',
  );
  const allowedOrigins = corsOriginsRaw
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
  app.use(
    helmet({
      crossOriginResourcePolicy: false,
      contentSecurityPolicy:
        nodeEnv === 'development'
          ? false
          : { directives: { defaultSrc: ["'self'"] } },
    }),
  );
  app.use(json({ limit: '8mb' }));
  app.use(urlencoded({ extended: true, limit: '8mb' }));
  app.enableCors({
    origin: allowedOrigins,
    credentials: true,
  });

  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      forbidNonWhitelisted: true,
    }),
  );

  app.useGlobalFilters(new GlobalExceptionFilter());
  app.useGlobalInterceptors(new ResponseInterceptor());
  app.useLogger(app.get(LoggerService));

  const swaggerConfig = new DocumentBuilder()
    .setTitle('Pharmacy Platform API Gateway')
    .setDescription(
      'Single API entrypoint for Pharmacy ERP, Ecommerce and POS frontend. ' +
        'All frontend requests must go through this gateway. Internal service URLs are for development/debug only. ' +
        'Authorization header is forwarded downstream. x-request-id is optional and is reused or generated by gateway.',
    )
    .setVersion('1.0')
    .addBearerAuth()
    .addApiKey(
      { type: 'apiKey', in: 'header', name: 'x-request-id' },
      'x-request-id',
    )
    .build();

  const swaggerDocument = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup('docs', app, swaggerDocument);

  const port = configService.get<number>('ports.gateway', 3000);

  await app.listen(port);
}

void bootstrap();
