export const EVENT_TYPES = {
  COMMERCE_ORDER_CREATED: 'commerce.order.created.v1',
  COMMERCE_ORDER_PAID: 'commerce.order.paid.v1',
  COMMERCE_PAYMENT_GATEWAY_INITIATED: 'commerce.payment.gateway.initiated.v1',
  COMMERCE_PAYMENT_GATEWAY_PAID: 'commerce.payment.gateway.paid.v1',
  COMMERCE_PAYMENT_GATEWAY_FAILED: 'commerce.payment.gateway.failed.v1',
  COMMERCE_PAYMENT_GATEWAY_CANCELED: 'commerce.payment.gateway.canceled.v1',
  OPERATION_INVENTORY_LOW_STOCK: 'operation.inventory.low_stock_detected.v1',
  OPERATION_BATCH_EXPIRING: 'operation.batch.expiring_detected.v1',
  OPERATION_RECEIPT_CREATED: 'operation.receipt.created.v1',
  OPERATION_STORE_VERIFY_REQUIRED: 'operation.store.verify_required.v1',
  REPORTING_REPORT_EXPORT_COMPLETED: 'reporting.report.export.completed.v1',
  REPORTING_REPORT_EXPORT_FAILED: 'reporting.report.export.failed.v1',
  REPORTING_SETTINGS_CHANGED: 'reporting.settings.changed.v1',
  NOTIFICATION_EVENT_CREATED: 'notification.event.created.v1',
  NOTIFICATION_DELIVERY_FAILED: 'notification.delivery.failed.v1',
  IDENTITY_USER_CREATED: 'identity.user.created.v1',
  IDENTITY_USER_ROLE_CHANGED: 'identity.user.role_changed.v1',
} as const;
